### ISSUE TITLE
DPC++ nightly support 

### ISSUE THREAD

**Issue by Luigi-Crisci** [intel/vscode-oneapi-environment-configurator#8]
Hi, 
I was trying to use the oneAPI extension with a DPC++ nightly version built from source, but I don't have any set_vars.sh script
Is there a way to make it works with DPC++ nightly build or do I need to download the entire oneAPI toolkit?

Thanks a lot

**Comment by sbobko** [comment]
Hi @Luigi-Crisci ,
If I understand correctly, do you mean these releases?:
https://github.com/intel/llvm/releases
Unfortunately, if there is no script for setting up the environment after the build, then we will not be able to add it. Alternatively, we could try adding a chain of environment configuration scripts, for example servers.sh (BaseKit) + startup.sh (DPC++) and so on. Do you need this option? Unfortunately, otherwise the amount of customization will be comparable to manual configuration and it doesn't make much sense to try to automate it.

**Comment by amakarev** [comment]
Hello. The extension uses scripts supplied with the toolkit, so without it it will not be possible to configure the environment via extension
